# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='sta', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=262202049, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_no',
            field=models.IntegerField(default=2012134090, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session',
            field=models.IntegerField(default=1999, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(default=4, max_length=4),
            preserve_default=False,
        ),
    ]
