# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0002_auto_20170203_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reg_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(),
        ),
    ]
