# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0003_auto_20170203_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='demouser',
            name='department',
            field=models.CharField(default='sta', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demouser',
            name='phone',
            field=models.IntegerField(default=2012134090),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demouser',
            name='reg_no',
            field=models.IntegerField(default=2012134090),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demouser',
            name='semester',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demouser',
            name='session',
            field=models.IntegerField(default=2012134090),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demouser',
            name='year',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
