# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0004_auto_20170203_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='session',
            field=models.CharField(max_length=7),
        ),
    ]
