# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryfine',
            name='text',
        ),
        migrations.RemoveField(
            model_name='libraryfine',
            name='title',
        ),
        migrations.AddField(
            model_name='libraryfine',
            name='amount_fined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libraryfine',
            name='book_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libraryfine',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='libraryfine',
            name='gender',
            field=models.CharField(choices=[(b'1', b'Male'), (b'2', b'Female')], default=1, max_length=1),
        ),
    ]
