# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_cashmemo_certificate_shahparanhall_std2_std6_transcript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STD2',
            new_name='S2',
        ),
    ]
