# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20170306_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmemo',
            name='amount_fined',
        ),
        migrations.RemoveField(
            model_name='cashmemo',
            name='book_count',
        ),
        migrations.RemoveField(
            model_name='cashmemo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='std6',
            name='amount_fined',
        ),
        migrations.RemoveField(
            model_name='std6',
            name='book_count',
        ),
        migrations.AddField(
            model_name='std6',
            name='certiricate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='course_modificatoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='drop_lab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='drop_theory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='duplicate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='exam_lab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='exam_theory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='extra1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='extra2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='extra3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='extra4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='extra5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='non_colligiate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='registration_late',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='total_lab',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='std6',
            name='total_theory',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
