# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20170306_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmemo',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='branch',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='moeny2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='money1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='money3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='name',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
