# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20170306_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shahparanhall',
            old_name='amount_fined',
            new_name='bank_no',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='amount_fined',
            new_name='honors_reg',
        ),
        migrations.RemoveField(
            model_name='shahparanhall',
            name='book_count',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='book_count',
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='bank_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='father_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='first_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='firstst_cgpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='fourth_cgpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='fourth_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='hons_first',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='mother_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='postc',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='postp',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='second_cgpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='second_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='thanap',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='thanc',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='third_cgpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='third_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='villagec',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='villagep',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='zillc',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='shahparanhall',
            name='zillp',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='transcript',
            name='address',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='transcript',
            name='discipline',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='transcript',
            name='exam_name_date',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='transcript',
            name='ms_reg',
            field=models.IntegerField(default=0),
        ),
    ]
