# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20170306_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='address',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='discipline',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='exam_name_date',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='honors_reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='letter',
            field=models.CharField(default=b'', max_length=2),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='nationlaity',
            field=models.CharField(default=b'Bangladeshi', max_length=30),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='school',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
